import { LandingNav } from '@/components/landing/landing-nav'
import { Footer } from '@/components/landing/footer'

export default function TermsPage() {
  return (
    <main className="relative min-h-screen flex flex-col">
      <LandingNav />
      <div className="flex-1 max-w-3xl mx-auto px-4 pt-32 pb-24 text-foreground-secondary">
        <h1 className="text-3xl font-bold text-foreground mb-8">Terms of Service</h1>
        <div className="space-y-6">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using AdaptFit AI, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Medical Disclaimer</h2>
            <p>AdaptFit AI provides fitness and nutritional suggestions generated by artificial intelligence. This information is for educational purposes only and should not replace professional medical advice. Always consult a physician before beginning any new exercise or diet program.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. User Accounts</h2>
            <p>You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.</p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
